### ISSUE TITLE
make: *** No rule to make target 'MinnowServer/example/src/main.c', needed by 'build/program.a'.  Stop.

### ISSUE THREAD

**Issue by 20ksaul** [RealTimeLogic/MinnowServer#1]
make: *** No rule to make target 'MinnowServer/example/src/main.c', needed by 'build/program.a'.  Stop.

After setting up the SharkSSL IDE and running the following commands I get the error above.

# Navigate to examples directory
cd ESP/esp-open-rtos/examples/
#Put the MinnowServer, the example, and JSON lib in the ms directory.
mkdir ms
cd ms
# Note that we do not need JSON and SMQ since these two componets are included in the SharkSSL IDE.
git clone https://github.com/RealTimeLogic/MinnowServer.git
# Navigate to the architecture directory
cd MinnowServer/doc/arch/
# Copy the two required files. All other files are included in the ESP8266 SharkSSL delivery
cp Makefile MinnowHwIntf.c ../../../
# The following enables compiling from withing the web IDE
chmod +x ms.sh; mv ms.sh ~/ESP/
# Navigate to the 'host build' make directory
cd ../../example/make/
# Amalgamate and compress www -> creates index.c
make packwww
# cd to the root of the example
cd ~/ESP/esp-open-rtos/examples/ms
# Build example and upload to the connected ESP8266
make test FLASH_MODE=dio ESPPORT=/dev/ttyUSB0

**Comment by surfskidude** [comment]
Do you get this error with [SharkSSL ESP8266 IDE](https://realtimelogic.com/downloads/sharkssl/ESP8266/) ?

**Comment by 20ksaul** [comment]
> Do you get this error with [SharkSSL ESP8266 IDE](https://realtimelogic.com/downloads/sharkssl/ESP8266/) ?

Yes I am

**Comment by surfskidude** [comment]
The instructions appear outdated, but it works if you ignore the errors. The following shows how I successfully compiled the Minnow Server Example:
![compile](https://github.com/RealTimeLogic/MinnowServer/assets/3975219/aefd8e95-6a3f-4e8a-acda-f0f1d4f1117e)

**Comment by 20ksaul** [comment]
> The instructions appear outdated, but it works if you ignore the errors. The following shows how I successfully compiled the Minnow Server Example: ![compile](https://private-user-images.githubusercontent.com/3975219/321377065-aefd8e95-6a3f-4e8a-acda-f0f1d4f1117e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDkxMTIsIm5iZiI6MTcxMjg0ODgxMiwicGF0aCI6Ii8zOTc1MjE5LzMyMTM3NzA2NS1hZWZkOGU5NS02YTNmLTRlOGEtYWNkYS1mMGYxZDRmMTExN2UuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTUyMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAwMDFmODZkOWM3MzQwMGNkNDVjMzEzMzA0NzA5MmQ3OWM0NTUzN2Q5Y2UwZmZmN2M2YzNlMjY2N2IwNDIyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0FtMIpEQrzSYoS1NDzYSoJKM4m2u7WG6otCLTO-miGk)

The error is fatal and will not allow the code to compile and upload.
![Screenshot 2024-04-11 112109](https://github.com/RealTimeLogic/MinnowServer/assets/44171473/23292e93-d148-419e-b8b7-abb06f0a9ffb)

**Comment by surfskidude** [comment]
It works for me, so I am not sure what's wrong; you just need to find out why it can't find main.c. See my compile log. Consider using an ESP32-S3 and the new and much easier to use Xedge32: https://realtimelogic.com/downloads/bas/ESP32/
